### ISSUE TITLE
Capitalization or not?

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/data-model#2]
There is a confusion between use of capitalization amongst the data-model. For example in the same document (D1.4) there exist both 
- `obeu-budgetphase:Draft` and `obeu-budgetphase:draft`
- `obeu-operation:Expenditure`  and `obeu-operation:expenditure`

So can you please clarify which one to use?

**Comment by jindrichmynarz** [comment]
That's a good catch. Capitalization of local names of `skos:Concept` IRIs [was corrected in this repository](https://github.com/openbudgets/data-model/commit/8399ef71cb2e8a6e9abea880bb05f8cb12b5be4a), but was not completely reflected in the D1.4 text. The preferred approach is to use lower-cased local names for `skos:Concept`s (as for any ABox resource). This was now corrected in [D1.5](https://docs.google.com/document/d/1wBA6-4krWuzD2N2RXHddGcIfNFOuLDXKiMIDCKnZRQU/edit#), which is an iteration of D1.4. Please refer to D1.5 to have the most up-to-date version of the OpenBudgets.eu data model with all fixes.
