### ISSUE TITLE
Update Data Model on server.

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/data-model#5]
@liyakun could you please update the Data Model loaded on server's triplestore?

**Comment by jindrichmynarz** [comment]
Note that you can use [this pipeline](https://github.com/openbudgets/pipeline-fragments/tree/master/obeu/load-obeu) to load the OpenBudgets.eu data model.

**Comment by liyakun** [comment]
@lavdim could you have a look at this issue?

**Comment by lavdim** [comment]
hi @jindrichmynarz , @skarampatakis , the pipeline given in the above link is executed successfully. How can I verify that the data model is updated successfully with the latest version?

**Comment by jindrichmynarz** [comment]
We don't do explicit versioning in RDF (as in `owl:versionInfo`). You can simply check whether the data model is loaded at all:

```sparql
ASK WHERE { GRAPH <http://data.openbudgets.eu/ontology> { [] ?p [] . } }
```

**Comment by skarampatakis** [comment]
I can confirm that I can find the Greek translations, so I suppose it is OK.
